# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.

# API Keys
currency.api.key=da8f8725a9a3fd222de9a9c04b9b038c
maps.api.key=AIzaSyAdAZ_UNOF3iTBw8TeXSWLlGvpGjEtJCGA
events.json.path=G:\\Term 2\\SOCM\\EventApp\\Events.json

