# WebServices Configuration

# Currency Service Configuration
currency.api.key=da8f8725a9a3fd222de9a9c04b9b038c
currency.api.url=http://api.exchangeratesapi.io/v1/latest

# Directions Service Configuration
directions.api.key=AIzaSyAdAZ_UNOF3iTBw8TeXSWLlGvpGjEtJCGA
directions.api.url=https://maps.googleapis.com/maps/api/directions/json

# Image Service Configuration (for Pixabay)
images.api.key=49345664-e289344f8497d7983c96d93f4